##CK2
create_CK2_bloodlines_decision = {
	picture = {
		reference = "gfx/interface/illustrations/decisions/decision_dynasty_house.dds"
	}
	decision_group_type = bloodline
	ai_potential = {
		always = yes
	}
	ai_check_interval = 1
	ai_will_do = {
		base = 100
	}

	is_shown = {
		NOT = {	
			is_target_in_global_variable_list = {	
				name = unavailable_bloodline_decisions
				target = flag:flag_bloodline
			}
		}
	}

	widget = {
		gui = "decision_view_widget_option_list_generic"
		controller = decision_option_list_controller
		decision_to_second_step_button = "SET_BLOODLINES"
		show_from_start = yes

		#圣人
		item = {
			value = saintly_bloodline
			is_shown = {
				has_trait = saint
				NOR = { 
					faith = { has_doctrine_parameter = tenet_ancestor_worship }
					has_saintly_bloodline = yes
				}
			}
			localization = saintly_bloodline
			ai_chance = { value = 0 }
		}
		#祖先崇拜
		item = {
			value = ancestor_worship_bloodline
			is_shown = {
				has_trait = saint
				faith = { has_doctrine_parameter = tenet_ancestor_worship }
				NOT = { has_ancestor_worship_bloodline = yes }
			}
			localization = ancestor_worship_bloodline
			ai_chance = { value = 0 }
		}
		#征服
		item = {
			value = pure_war_bloodline
			is_shown = {
				any_character_war = {
					count = 15
					is_war_leader = root
					OR = {
						AND = {
							primary_defender = root
							defender_war_score = 100
						}
						AND = {
							primary_attacker = root
							attacker_war_score = 100
						}
					}
				}
				NOT = { has_pure_war_bloodline = yes }
			}
			localization = pure_war_bloodline
			ai_chance = { value = 0 }
		}
		#和平
		item = {
			value = pure_peace_bloodline
			is_shown = {
				days_of_continuous_peace >= 10850
				NOT = { has_pure_peace_bloodline = yes }
			}
			localization = pure_peace_bloodline
			ai_chance = { value = 0 }
		}
		#谋杀
		item = {
			value = pure_murder_bloodline
			is_shown = {
				any_killed_character = { count >= 30 }
				NOT = { has_pure_murder_bloodline = yes }
			}
			localization = pure_murder_bloodline
			ai_chance = { value = 0 }
		}
		#建设
		item = {
			value = pure_constructor_bloodline
			is_shown = {
				any_county_province = {
					count >= 30
					OR = {
						has_holding_type = city_holding
						has_holding_type = church_holding
						has_holding_type = castle_holding
					}
				}
				NOT = { has_pure_constructor_bloodline = yes }
			}
			localization = pure_constructor_bloodline
			ai_chance = { value = 0 }
		}
		#混合
		item = {
			value = hybrid_bloodline
			is_shown = {
				OR ={
					AND = {
						any_killed_character = { count >= 20 }
						any_character_war = {
							count = 15
							is_war_leader = root
							OR = {
								AND = {
									primary_defender = root
									defender_war_score = 100
								}
								AND = {
									primary_attacker = root
									attacker_war_score = 100
								}
							}
						}
						NOT = { has_trait = hybrid_murder_war_bloodline }
					}
					AND = {
						any_killed_character = { count >= 20 }
						days_of_continuous_peace >= 5475
						NOT = { has_trait = hybrid_murder_peace_bloodline }
					}
					AND = {
						any_killed_character = { count >= 15 }
						any_county_province = {
							count >= 15
							OR = {
								has_holding_type = city_holding
								has_holding_type = church_holding
								has_holding_type = castle_holding
							}
						}
						NOT = { has_trait = hybrid_murder_builder_bloodline }
					}
					AND = {
						days_of_continuous_peace >= 5475
						any_county_province = {
							count >= 15
							OR = {
								has_holding_type = city_holding
								has_holding_type = church_holding
								has_holding_type = castle_holding
							}
						}
						NOR = { 
							has_trait = hybrid_peace_architect_bloodline
							has_trait = hybrid_peace_castellan_bloodline
							has_trait = hybrid_peace_monumental_bloodline
						}
					}
				}
			}
			localization = hybrid_bloodline
			ai_chance = { value = 0 }
		}
		#行为/活动
		item = {
			value = action_bloodline
			is_shown = {
				OR = {
					#海盗
					AND = {
						OR = {
							culture = { has_cultural_pillar = heritage_north_germanic }
							has_culture = culture:norman
						}
						highest_held_title_tier >= tier_kingdom
						has_trait = viking
						NOR = { 
							has_trait = seaking_bloodline 
							has_trait = seaqueen_bloodline 
						}
					}
					#泰乌塔 
					#法拉里斯
					#决斗者 
					#传说之始
					AND = {
						is_dynast = yes
						highest_held_title_tier >= tier_kingdom
						NOT = { has_trait = family_bloodline }
						dynasty = {
							any_dynasty_member = {
								count >= 10
								is_independent_ruler = yes
								highest_held_title_tier >= tier_kingdom
							}
						}
					}
				}
			}
			localization = action_bloodline
			ai_chance = { value = 0 }
		}
		#头衔类
		item = {
			value = formation_bloodline
			is_shown = {
				OR = {
					#斯拉维亚
					AND = {
						has_title = title:k_norway
						NOR = { 
							has_trait = lcr_male 
							has_trait = lcr_female 
						}
					}
					#罗马
					AND = {
						has_title = title:h_roman_empire
						NOR = { 
							has_trait = lcr_bloodline_male 
							has_trait = lcr_bloodline_female 
						}
					}
					#以色列
					AND = {
						has_title = title:k_israel
						faith.religion = religion:judaism_religion
						NOR = { 
							has_trait = israel_bloodline_male 
							has_trait = israel_bloodline_female 
						}
					}
					#印度
					AND = {
						has_title = title:h_india
						faith.religion = religion:hinduism_religion
						NOR = {
							has_trait = samrat_chakravartin_bloodline_male 
							has_trait = samrat_chakravartin_bloodline_female 
						}
					}
					#波斯
					AND = {
						has_title = title:e_persia
						faith.religion = religion:zoroastrianism_religion
						NOR = { 
							has_trait = saoshyant_bloodline_male 
							has_trait = saoshyant_bloodline_female 
						}
					}
					#中国
					AND = {
						has_title = title:h_china
						NOR = { 
							has_trait = chinese_imperial_bloodline_male 
							has_trait = chinese_imperial_bloodline_female
						}
					}
					#蒙古
					AND = {
						has_title = title:e_mongol_empire
						NOR = { 
							has_trait = genghis_khan_bloodline_male
							has_trait = genghis_khan_bloodline_female
						}
					}
					#海外帝国
					AND = {
						has_title = title:e_outremer
						NOR = { 
							has_trait = lord_of_outremer_bloodline_male
							has_trait = lord_of_outremer_bloodline_female 
						}
					}
					#拜占庭毁灭者 
					AND = {
						has_title = title:e_latin_empire
						NOR = { 
							has_trait = destroyer_of_byzantium_bloodline_male
							has_trait = destroyer_of_byzantium_bloodline_female 
						}
					}
				}
			}
			localization = formation_bloodline
			ai_chance = { value = 0 }
		}

	}

	effect = {

	}
	
}

